/*
Insertar manualmente registros a la tabla
*/
INSERT INTO FURNITURE (FURNITURE_ID , FURNITURE_NAME, FURNITURE_FECHA_REGISTRO, FURNITURE_DESCRIPTION)
VALUES
    (NEXT VALUE FOR "PUBLIC"."FURNITURE_SEQ_ID"	, 'Table', CURRENT_DATE, 'new'),
    (NEXT VALUE FOR "PUBLIC"."FURNITURE_SEQ_ID"	, 'Chair', CURRENT_DATE, 'new'),
    (NEXT VALUE FOR "PUBLIC"."FURNITURE_SEQ_ID"	, 'Sofa', CURRENT_DATE, 'old'),
    (NEXT VALUE FOR "PUBLIC"."FURNITURE_SEQ_ID"	, 'Door', CURRENT_DATE, 'old');



/*
Para crear  nueva tabla
*/
-- CREATE SEQUENCE IF NOT EXISTS FURNITURE_SEQ3 START WITH 1 INCREMENT BY 1;
--
-- CREATE TABLE FURNITURE3 (
--                             FURNITURE_ID BIGINT DEFAULT NEXT VALUE FOR FURNITURE_SEQ3 PRIMARY KEY,
--                             FURNITURE_DESCRIPTION VARCHAR(255),
--                             FURNITURE_FECHA_REGISTRO DATE,
--                             FURNITURE_NAME VARCHAR(255)
-- );
--
-- INSERT INTO FURNITURE3 (FURNITURE_ID , FURNITURE_DESCRIPTION, FURNITURE_FECHA_REGISTRO, FURNITURE_NAME)
-- VALUES
--     (NEXT VALUE FOR "PUBLIC"."FURNITURE_SEQ3"	, 'pruebaaaaaaaaa', CURRENT_DATE, 'Silla Elegante');